/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lichong_capturer_CapturePacket */

#ifndef _Included_com_example_lichong_capturer_CapturePacket
#define _Included_com_example_lichong_capturer_CapturePacket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lichong_capturer_CapturePacket
 * Method:    setMonitor
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lichong_capturer_CapturePacket_setMonitor
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lichong_capturer_CapturePacket
 * Method:    startCapture
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lichong_capturer_CapturePacket_startCapture
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lichong_capturer_CapturePacket
 * Method:    endCapture
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lichong_capturer_CapturePacket_endCapture
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
